### PR TITLE
feat: migrate to capacitor 6

### PR DESCRIPTION
**Pull request by niconaso**
Migration to [Capacitor 6](https://capacitorjs.com/docs/updating/plugins/6-0)

### CODE REVIEW

**Comment by Snouzy** [comment]
I'm looking forward to it 😃 good job!

**Comment by EinfachHans** [comment]
@RaphaelWoude are you still maintaining this plugin? Can you merge this PR? 😊

**Comment by alexdabast** [comment]
@RaphaelWoude couldn't agree any more could you accept this merge ? :)

**Review by gasci — APPROVED** [review]

**Comment by afilp** [comment]
Can you please merge this? Thanks a lot!

**Comment by RaphaelWoude** [comment]
Sorry for the wait. Not having a lot of time to work on Open Source at the moment.
Looking at the pull request now.

**Comment by RaphaelWoude** [comment]
Everything looks fine except for the verify-ios action. This was because our action was still running on IOS 12 even through this was set to the latest. I have updated this to IOS 14 for now. Please pull the changes from main.

**Comment by RaphaelWoude** [comment]
https://github.com/RaphaelWoude/capacitor-native-settings/commit/527e1cb63498fa0e583a717d592e03b3f4b52e97

**Comment by niconaso** [comment]
> Everything looks fine except for the verify-ios action. This was erroring out because our action was still running on IOS 12 even through this was set to the latest. Capacitor 6 needs IOS 14 with XCode 15. I have updated this to IOS 14 for now. Please pull the changes from main.

@RaphaelWoude Done!

**Review by RaphaelWoude — APPROVED** [review]

**Comment by EinfachHans** [comment]
Thabk you everyone, one plugin less on my list to update to v6 😃

**Comment by gasci** [comment]
I understand you brother. I am in the same situation.

**Pull request merged**
