### PR TITLE
Prepare a capacitor 5 compatible version

### PR DESCRIPTION
**Pull request by ptmkenny**
This PR is a follow-up to https://github.com/RaphaelWoude/capacitor-native-settings/issues/30.

These are the changes required according to the [plugin migration guide](https://capacitorjs.com/docs/next/updating/plugins/5-0).

### CODE REVIEW

**Comment by RaphaelWoude** [comment]
Thank you for your contribution. Would you be able to fix the linting errors for Android?

**Comment by ptmkenny** [comment]
Hmm... I just checked the error, but I don't understand what it wants.  It [may be an error with Capacitor itself?](https://github.com/ionic-team/capacitor/issues/6296)

**Comment by NePheus** [comment]
You missed some changes in your PR.
Have a look to https://capacitorjs.com/docs/next/updating/plugins/5-0
You have to remove the package from the AndroidManifest.xml and they updated the guide to use gradle 8.

**Comment by ptmkenny** [comment]
@NePheus Thanks, I hadn't seen that the gradle version had been bumped again, and I had failed to remove the package attribute.  It should be fixed now after the last two commits.

**Comment by NePheus** [comment]
I think the PR fails because JavaVersion.VERSION_11 is set in the compile options in the build.gradle. It must be version 17 after this migration.

**Comment by ptmkenny** [comment]
@NePheus Thanks for this hint.  Would you happen to know how to set version 17?  I tried doing so in [this commit](https://github.com/RaphaelWoude/capacitor-native-settings/pull/32/commits/cb23c3e9e6a6253b0b9eefa2f06ec05ee349de03) but I still get an error in the automated tests.  Honestly I don't know how to fix this so any insight would be much appreciated.

**Comment by NePheus** [comment]
Maybe you should have a look how capacitor implemented it in their plugins.
https://github.com/ionic-team/capacitor-plugins/blob/main/app/android/build.gradle

**Comment by dallastjames** [comment]
👋 Hello! I'm just following up from an issue over on the Cap repo. You can also checkout our plugin upgrade guide which should be updated for the latest gradle and java changes from the latest beta version [here](https://capacitorjs.com/docs/next/updating/plugins/5-0#update-to-java-17). We've also been working on an automated migration path for plugins (a simple `npx` command) to make this jump for you that will be available soon. Keep an eye out  for release day and we'll have all the details for that!

**Comment by ptmkenny** [comment]
Changes I made to get this working:

* Added `setup-java` action to use version 17 instead of 11 (the GitHub ubuntu image defaults to 11)
* Bumped the capacitor dependencies in `package.json` from 4 to `next`.  This will need to be set back to 5 when capacitor 5 gets its official release.
* Updated Github Actions from node v14 to v18 because v14 support ended two days ago.
* Bumped the github action versions for checkout + setup-node from 2 to 3 to clean up the deprecation warnings.
* Removed the `test` step from the GitHub workflow.  This is because it seems the plugin doesn't define any tests, and after updating to v18, this step started failing.

**Comment by NePheus** [comment]
Great! But now you have many commits that would be pushed to develop. I would suggest you to rebase/sqash your commits, or otherwise create a new branch with only the commits that are needed. Thanks for your work :)

**Comment by ptmkenny** [comment]
@NePheus Thanks, I can do that if necessary, but the commits can automatically be squashed with the "Squash and merge" button here on GitHub (or `merge --squash`).

**Comment by RaphaelWoude** [comment]
Will be looking at the PR very soon. Just saw that capacitor v5 also released. So this will be a good time to get another version out.

**Pull request merged**
